In [1]:
import numpy as np

In [2]:
# Consider the code
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [ ]:
#In Python, the built-in data type "list" represents an ordered collection of elements, which can be of different data types. Whereas, "array" is a module in Python that provides support for creating homogeneous arrays of fixed-size.
list_ = [1, 2, 3, "four", "five"]
array_list = array.array('i', [1, 2, 3, 4, 5])

print(type(list_))
print(type(array_list))


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.

In [ ]:
#Since the original "list_" variable contains a mix of integer and string data types, the resulting "array_list" variable will only contain the integer values from the original list, converted to the integer data type.
import numpy as np

list_ = [1, 2, 3, "four", "five"]
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
for elem in list_:
    print(type(elem))

# Print data types of elements in array_list
for elem in array_list:
    print(type(elem))


import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#1
num_array.shape
# Shape basically returns the dimensions of the array.

(2, 3)

In [11]:
#2
num_array.size
# Size function returns the number of the elements in the array

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [12]:
# To create an array of zeros.
zero_array = np.zeros((3,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [17]:
#To create an Identity matrix we use the eye funtion.
import numpy.matlib as mt
Identity_matrix = mt.eye(5)
Identity_matrix

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])